const keywords = [
    "Project Management",
    "Construction Management",
    "Construction Engineering",
    "Civil Engineering",
    "Inspection Services",
    "Aerial/Photogrammetric Mapping Services",
    "Aerial Photography",
    "Environmental",
    "Land Surveying",
    "Document Control",
    "Engineering",
    "Integrated Systems & CAD/CAM Systems",
    "Management Information Systems",
    "Traffic Engineer",
    "Computer Programming",
    "Public Relations",
    "Community Relations",
    "Public Outreach",
    "Augmented Reality",
    "BIM",
    "Building Information Modeling",
    "Artificial Intelligence",
    "Constructabilty Review",
    "Safety security verification",
    "System integration",
    "Safety management",
    "Quality management",
    "Project Controls",
    "Project Management",
    "Construction Management",
    "Construction Engineering",
    "Civil Engineering",
    "Inspection Services",
    "Photogrammetric",
    "Aerial Photography",
    "Environmental",
    "Land Surveying",
    "Document Control",
    "Engineering",
    "Integrated Systems",
    "CAD Systems",
    "CAM Systems",
    "Management Information Systems",
    "Traffic Engineer",
    "Computer Programming",
    "Public Relations",
    "Community Relations",
    "Public Outreach",
    "Data Analytics",
    "Data Science",
    "Data Processing",
    "Design Build",
    "Design-Build",
    "Design-Build Entity",
    "DBE",
    "Criteria Document",
    "Schematic Design",
    "Design Development",
    "Construction Documents",
    "Basis of Design",
    "Cost Modeling",
    "Design Proposal",
    "Guaranteed Maximum Price",
    "Integrated Project Delivery",
    "Life Cycle Cost",
    "Life Cycle Cost Analysis",
    "Risk Register",
    "Electrical",
    "Lighting",
    "Fixtures",
    "Construction",
    "Materials",
    "Supply",
    "Tools",
    "Utilities",
    "Overhead Wire",
    "Underground Wire",
    "Overhead/Underground Wire",
    "Underground Pipe",
    "Underground Conduit",
    "Switchgear",
    "Panel Boards",
    "Breakers",
    "Fuses",
    "Electrical Equipment",
    "Ballasts",
    "Life Safety",
    "Low Voltage Wiring",
    "LED Lighting",
    "Industrial Lighting",
    "Commercial Lighting",
    "Residential Lighting",
    "Power",
    "Commercial Power",
    "Residential Power",
    "Industrial Power",
    "Indoor Lighting",
    "Outdoor Lighting",
    "Explosion Proof Lighting",
    "Bidding",
    "PVC Conduit, Wires",
    "Conduit",
    "Fittings",
    "Switchboards",
    "Transformers",
    "Wireways",
    "Electrical Enclosures",
    "Power Conditioning Equipment",
    "Power Generation Control Equipment",
    "Lighting Controls",
    "General Requirements",
    "Floor Sealant",
    "Metal Fabrication",
    "Glazing",
    "Exterior Glazing",
    "Interior Construction",
    "Clean Up",
    "Tower Cranes",
];

module.exports = keywords.join("|");
