const keywords = [
    "Project Management",
    "Construction Management",
    "Construction Engineering",
    "Civil Engineering",
    "Inspection Services",
    "Aerial/Photogrammetric Mapping Services",
    "Aerial Photography",
    "Environmental",
    "Land Surveying",
    "Document Control",
    "Engineering",
    "Integrated Systems & CAD/CAM Systems",
    "Management Information Systems",
    "Traffic Engineer",
    "Computer Programming",
    "Public Relations",
    "Community Relations",
    "Public Outreach",
    "Augmented Reality",
    "BIM",
    "Building Information Modeling",
    "Artificial Intelligence",
    "Constructabilty Review",
    "Safety security verification",
    "System integration",
    "Safety management",
    "Quality management",
    "Project Controls",
    "Project Management",
    "Construction Management",
    "Construction Engineering",
    "Civil Engineering",
    "Inspection Services",
    "Photogrammetric",
    "Aerial Photography",
    "Environmental",
    "Land Surveying",
    "Document Control",
    "Engineering",
    "Integrated Systems",
    "CAD Systems",
    "CAM Systems",
    "Management Information Systems",
    "Traffic Engineer",
    "Computer Programming",
    "Public Relations",
    "Community Relations",
    "Public Outreach",
    "Data Analytics",
    "Data Science",
    "Data Processing",
    "Design Build",
    "Design-Build",
    "Design-Build Entity",
    "DBE",
    "Criteria Document",
    "Schematic Design",
    "Design Development",
    "Construction Documents",
    "Basis of Design",
    "Cost Modeling",
    "Design Proposal",
    "Guaranteed Maximum Price",
    "Integrated Project Delivery",
    "Life Cycle Cost",
    "Life Cycle Cost Analysis",
    "Risk Register",
];

module.exports = keywords.join("|");
